
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class SintacticoA1 extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public SintacticoA1() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public SintacticoA1(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public SintacticoA1(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\010\000\002\002\004\000\002\002\003\000\002\003" +
    "\005\000\002\005\005\000\002\004\010\000\002\004\010" +
    "\000\002\004\007\000\002\004\007" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\007\000\004\004\006\001\002\000\004\002\000\001" +
    "\002\000\004\002\011\001\002\000\004\020\007\001\002" +
    "\000\004\021\010\001\002\000\004\002\uffff\001\002\000" +
    "\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\007\000\006\002\004\003\003\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$SintacticoA1$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$SintacticoA1$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$SintacticoA1$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public void syntax_error(Symbol s){ 
        System.out.println("Error Sintáctico en la Línea " + (s.left) +
        " Columna "+s.right+ ". No se esperaba este componente: " +s.value+"."); 
    } 

    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{ 
        System.out.println("Error síntactico irrecuperable en la Línea " + 
        (s.left)+ " Columna "+s.right+". Componente " + s.value + 
        " no reconocido."); 
    }  


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$SintacticoA1$actions {
  private final SintacticoA1 parser;

  /** Constructor */
  CUP$SintacticoA1$actions(SintacticoA1 parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$SintacticoA1$do_action_part00000000(
    int                        CUP$SintacticoA1$act_num,
    java_cup.runtime.lr_parser CUP$SintacticoA1$parser,
    java.util.Stack            CUP$SintacticoA1$stack,
    int                        CUP$SintacticoA1$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$SintacticoA1$result;

      /* select the action based on the action number */
      switch (CUP$SintacticoA1$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$SintacticoA1$stack.elementAt(CUP$SintacticoA1$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$SintacticoA1$stack.elementAt(CUP$SintacticoA1$top-1)).right;
		String start_val = (String)((java_cup.runtime.Symbol) CUP$SintacticoA1$stack.elementAt(CUP$SintacticoA1$top-1)).value;
		RESULT = start_val;
              CUP$SintacticoA1$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$SintacticoA1$stack.elementAt(CUP$SintacticoA1$top-1)), ((java_cup.runtime.Symbol)CUP$SintacticoA1$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$SintacticoA1$parser.done_parsing();
          return CUP$SintacticoA1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= ESTADISTICO 
            {
              String RESULT =null;

              CUP$SintacticoA1$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$SintacticoA1$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoA1$stack.peek()), RESULT);
            }
          return CUP$SintacticoA1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // ESTADISTICO ::= generarreporteestadistico llavea llavec 
            {
              String RESULT =null;

              CUP$SintacticoA1$result = parser.getSymbolFactory().newSymbol("ESTADISTICO",1, ((java_cup.runtime.Symbol)CUP$SintacticoA1$stack.elementAt(CUP$SintacticoA1$top-2)), ((java_cup.runtime.Symbol)CUP$SintacticoA1$stack.peek()), RESULT);
            }
          return CUP$SintacticoA1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // GLOBALES ::= definirglobales llavea llavec 
            {
              String RESULT =null;

              CUP$SintacticoA1$result = parser.getSymbolFactory().newSymbol("GLOBALES",3, ((java_cup.runtime.Symbol)CUP$SintacticoA1$stack.elementAt(CUP$SintacticoA1$top-2)), ((java_cup.runtime.Symbol)CUP$SintacticoA1$stack.peek()), RESULT);
            }
          return CUP$SintacticoA1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // INSTRUCCIONES ::= INSTRUCCIONES sstring variable igual cadena pcoma 
            {
              String RESULT =null;

              CUP$SintacticoA1$result = parser.getSymbolFactory().newSymbol("INSTRUCCIONES",2, ((java_cup.runtime.Symbol)CUP$SintacticoA1$stack.elementAt(CUP$SintacticoA1$top-5)), ((java_cup.runtime.Symbol)CUP$SintacticoA1$stack.peek()), RESULT);
            }
          return CUP$SintacticoA1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // INSTRUCCIONES ::= INSTRUCCIONES ddouble variable igual decimal pcoma 
            {
              String RESULT =null;

              CUP$SintacticoA1$result = parser.getSymbolFactory().newSymbol("INSTRUCCIONES",2, ((java_cup.runtime.Symbol)CUP$SintacticoA1$stack.elementAt(CUP$SintacticoA1$top-5)), ((java_cup.runtime.Symbol)CUP$SintacticoA1$stack.peek()), RESULT);
            }
          return CUP$SintacticoA1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // INSTRUCCIONES ::= ddouble variable igual decimal pcoma 
            {
              String RESULT =null;

              CUP$SintacticoA1$result = parser.getSymbolFactory().newSymbol("INSTRUCCIONES",2, ((java_cup.runtime.Symbol)CUP$SintacticoA1$stack.elementAt(CUP$SintacticoA1$top-4)), ((java_cup.runtime.Symbol)CUP$SintacticoA1$stack.peek()), RESULT);
            }
          return CUP$SintacticoA1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // INSTRUCCIONES ::= sstring variable igual cadena pcoma 
            {
              String RESULT =null;

              CUP$SintacticoA1$result = parser.getSymbolFactory().newSymbol("INSTRUCCIONES",2, ((java_cup.runtime.Symbol)CUP$SintacticoA1$stack.elementAt(CUP$SintacticoA1$top-4)), ((java_cup.runtime.Symbol)CUP$SintacticoA1$stack.peek()), RESULT);
            }
          return CUP$SintacticoA1$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$SintacticoA1$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$SintacticoA1$do_action(
    int                        CUP$SintacticoA1$act_num,
    java_cup.runtime.lr_parser CUP$SintacticoA1$parser,
    java.util.Stack            CUP$SintacticoA1$stack,
    int                        CUP$SintacticoA1$top)
    throws java.lang.Exception
    {
              return CUP$SintacticoA1$do_action_part00000000(
                               CUP$SintacticoA1$act_num,
                               CUP$SintacticoA1$parser,
                               CUP$SintacticoA1$stack,
                               CUP$SintacticoA1$top);
    }
}

}
