
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores.A2;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int doo = 12;
  public static final int suma = 32;
  public static final int resta = 33;
  public static final int require = 48;
  public static final int falsee = 7;
  public static final int switchh = 13;
  public static final int log = 18;
  public static final int coma = 23;
  public static final int igual = 25;
  public static final int multiplicacion = 34;
  public static final int caracter = 42;
  public static final int dpuntos = 26;
  public static final int let = 4;
  public static final int diferencia = 45;
  public static final int llavec = 20;
  public static final int llavea = 19;
  public static final int elsee = 9;
  public static final int igualacion = 46;
  public static final int casee = 14;
  public static final int andd = 30;
  public static final int classe = 2;
  public static final int menor = 28;
  public static final int comentarioo = 40;
  public static final int var = 3;
  public static final int console = 17;
  public static final int iff = 8;
  public static final int constt = 5;
  public static final int truee = 6;
  public static final int EOF = 0;
  public static final int parentesisc = 22;
  public static final int whilee = 11;
  public static final int error = 1;
  public static final int parentesisa = 21;
  public static final int maigual = 44;
  public static final int pcoma = 24;
  public static final int mayor = 29;
  public static final int breakk = 15;
  public static final int meigual = 43;
  public static final int punto = 47;
  public static final int forr = 10;
  public static final int defaultt = 16;
  public static final int id = 39;
  public static final int orr = 31;
  public static final int not = 27;
  public static final int division = 35;
  public static final int comentarioomu = 41;
  public static final int decimal = 38;
  public static final int modulo = 36;
  public static final int cadena = 37;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "classe",
  "var",
  "let",
  "constt",
  "truee",
  "falsee",
  "iff",
  "elsee",
  "forr",
  "whilee",
  "doo",
  "switchh",
  "casee",
  "breakk",
  "defaultt",
  "console",
  "log",
  "llavea",
  "llavec",
  "parentesisa",
  "parentesisc",
  "coma",
  "pcoma",
  "igual",
  "dpuntos",
  "not",
  "menor",
  "mayor",
  "andd",
  "orr",
  "suma",
  "resta",
  "multiplicacion",
  "division",
  "modulo",
  "cadena",
  "decimal",
  "id",
  "comentarioo",
  "comentarioomu",
  "caracter",
  "meigual",
  "maigual",
  "diferencia",
  "igualacion",
  "punto",
  "require"
  };
}

