
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores.A1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ddouble = 10;
  public static final int cadena = 24;
  public static final int decimal = 25;
  public static final int parentesisc = 17;
  public static final int coma = 20;
  public static final int parentesisa = 16;
  public static final int archivo = 30;
  public static final int pcoma = 21;
  public static final int tituloy = 29;
  public static final int titulox = 28;
  public static final int graficabarras = 5;
  public static final int corchetec = 19;
  public static final int puntajeespecífico = 8;
  public static final int titulo = 11;
  public static final int corchetea = 18;
  public static final int ejex = 13;
  public static final int dolar = 23;
  public static final int igual = 22;
  public static final int EOF = 0;
  public static final int sstring = 9;
  public static final int variable = 26;
  public static final int error = 1;
  public static final int definirglobales = 3;
  public static final int comentarioomu = 32;
  public static final int graficapie = 6;
  public static final int graficalineas = 7;
  public static final int comentarioo = 31;
  public static final int llavec = 15;
  public static final int valores = 12;
  public static final int dpuntos = 27;
  public static final int llavea = 14;
  public static final int generarreporteestadistico = 2;
  public static final int compare = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "generarreporteestadistico",
  "definirglobales",
  "compare",
  "graficabarras",
  "graficapie",
  "graficalineas",
  "puntajeespecífico",
  "sstring",
  "ddouble",
  "titulo",
  "valores",
  "ejex",
  "llavea",
  "llavec",
  "parentesisa",
  "parentesisc",
  "corchetea",
  "corchetec",
  "coma",
  "pcoma",
  "igual",
  "dolar",
  "cadena",
  "decimal",
  "variable",
  "dpuntos",
  "titulox",
  "tituloy",
  "archivo",
  "comentarioo",
  "comentarioomu"
  };
}

